version: '3.7'

services:
#  config-server:
#    image: rausouza/microsservices-udemy/mmv2-spring-cloud-config-server:0.0.1-SNAPSHOT
#    mem_limit: 700m
#    ports:
#       - "8888:8888"
#    networks:
#      - "currency-network"

  limits-service:
    image: rausouza/microsservices-udemy/mmv2-limits-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - "currency-network"

  eureka-naming-server:
    image: rausouza/microsservices-udemy/mmv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - "currency-network"

  currency-exchange:
    image: rausouza/microsservices-udemy/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
       - "8000:8000"
    networks:
      - "currency-network"
    depends_on:
      - eureka-naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-naming-server:8761/eureka

  currency-conversion:
    image: rausouza/microsservices-udemy/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - "currency-network"
    depends_on:
      - eureka-naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-naming-server:8761/eureka
      CURRENCY.EXCHANGE.SERVICEURL: http://currency-exchange:8000/currency-exchange/from/USD/to/BRL

  api-gateway:
    image: rausouza/microsservices-udemy/mmv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - "currency-network"
    depends_on:
      - eureka-naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-naming-server:8761/eureka

networks:
  currency-network: